AlsHistory <- read.csv("C:/Temp/AlsHistory.CSV")
DeathData <- read.csv("C:/Temp/DeathData.CSV")
demographics <- read.csv("C:/Temp/demographics.CSV")
Fvc <- read.csv("C:/Temp/Fvc.CSV")
#extract information (demographics)
head(demographics)
DEMOGRAPHICS <- data.frame(demographics$subject_id, demographics$Age, demographics$Sex)
colnames(DEMOGRAPHICS) <- c("subject_id", "age", "sex")
head(DEMOGRAPHICS)
#DeathData
head(DeathData)
DEATHDATA <- data.frame(DeathData$subject_id, DeathData$Subject_Died)
#AlsHistory(type of onset site)
head(AlsHistory)
#Fvc
#ALSFRS_df_firsttime에다가 cluster1이라는 새로운 column을 만들어서 delta=0일때 각 환자가 속했던 cluster를 기입해보기.
ALSFRS_df_firsttime$Cluster1 <- c(km.ALSFRS$cluster)
#cluster에다가 age, sex column 추가
ALSFRS_df_firsttime1 <- merge(ALSFRS_df_firsttime, DEMOGRAPHICS)
#see difference between cluster(age, sex)
library(dplyr)
group_by(ALSFRS_df_firsttime1, Cluster1) %>%
summarise(age=mean(age, na.rm=TRUE), sex=mean(sex=="Male"))
boxplot(age~Cluster1, data=ALSFRS_df_firsttime1, varwidth=TRUE, xlab="Cluster", ylab="age")
mosaicplot(Cluster1~sex, data=ALSFRS_df_firsttime1)
#차이가 유의한지 확인하기 위해 ANOVA검정을 시행(age)
sapply(ALSFRS_df_firsttime1, class)
ALSFRS_df_firsttime1 <-transform(ALSFRS_df_firsttime1, Cluster1=factor(Cluster1))
aov(age~Cluster1, data=ALSFRS_df_firsttime1)
summary(aov(age~Cluster1, data=ALSFRS_df_firsttime1))
bartlett.test(age~Cluster1, data=ALSFRS_df_firsttime1)
#차이가 유의한지 보기위해 chi-square검정 시행(sex)
table(ALSFRS_df_firsttime1$Cluster1, ALSFRS_df_firsttime1$sex)
chisq.test(ALSFRS_df_firsttime1$Cluster1, ALSFRS_df_firsttime1$sex, correct=FALSE)